# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=200)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('support_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-addDate'],
            },
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(default='', max_length=200)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-writeDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='essays/')),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addDate'],
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='blog/images/')),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addDate'],
            },
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addDate'],
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=50)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addDate'],
            },
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(default='', max_length=200)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-writeDate'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(default='', max_length=200)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-writeDate'],
                'abstract': False,
            },
        ),
    ]
