# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(max_length=50)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='')),
                ('label1', models.CharField(default='', max_length=10)),
                ('label2', models.CharField(default='', max_length=10)),
                ('label3', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(max_length=50)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='')),
                ('label1', models.CharField(default='', max_length=10)),
                ('label2', models.CharField(default='', max_length=10)),
                ('label3', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('introduction', models.CharField(max_length=50)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('modifyDate', models.DateTimeField(auto_now=True)),
                ('words', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
