# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_storge_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storge',
            name='writDate',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 20, 19, 50, 19, 647810)),
        ),
    ]
